stages:
  - publish
  - deploy_dev


include:
  - project: 'sgsinfra/gitlab-ci-template'
    ref: master
    file:
      - "/build/.build_common.yml"
      - "/build/.publish_common.yml"
      - "/deploy/.deploy_common.yml"
 
publish:
  stage: publish
  extends:
    - .publish_common
  variables:
    ENV: "dev"
    IMAGE_NAME: "innoco-client"

deploy_dev:
  stage: deploy_dev
  extends:
    - .deploy_common
  variables:
    ENV: "dev"
    IMAGE_NAME: "innoco-client"
