import Head from 'next/head';
import { Button, SvgIcon } from '@components/Common';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>danbii</div>
      <SvgIcon type="down-icon" />
      <Button variant="auth">버튼</Button>
    </>
  );
}
